package csu.agent.search;

public enum State {
    WillClearPath,
    ClearingBlock,
    Exploring,
    ExploringRandom,
    LoadingHuman,
    UnloadingHuman,
    RescuingHuman,
    TakingCivilianToRefuge,
    GoingToRefugeToRefillWater,
    WillSaveHuman,
    Extinguishing,
    GoingToBlockedRoad,
    MovingToFire,
    MovingToFireArea,
    MovingToRefuge,
    FillingWater,
    Waiting,
    GoingToFireRegion,
    Inactive, MovingToHuman,
    SavingMyself,PFSavingMyself,otherAgentSavingMyself,
    MovingToRegion,
    GoingToGoalToClearPath,
    GoingToStartToClearPath,
    ClearingPath,
    SavedByOtherAgent,
    HumanIsHelpless,
    MovingToBlockAtCurrentLocation,
    GettingCloserToBlock,
    ClearingBlocksToPath,
    ClearingAllBlocksAtLocation,
    ClearingCurrentRoad,
    BuriedResting,
    StuckResting,
    MovingToBlockedRoad,
   ClearingRefugeEntrance, ClearingAnnoyingBlock}
